PyEditorial/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(('content.urls', 'content'), namespace='content')),
    path('accounts/', include("django.contrib.auth.urls"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('search/', views.Search.as_view(), name='search'),
    path('blog/', views.Blog.as_view(), name='blog'),
    path('create/blog/', views.BlogCreateView.as_view(), name='blog_create'),
    path('create/blog_category/', views.BlogCategoryCreateView.as_view(), name='blog_category_create'),
    path('blog/<int:pk>/', views.BlogArchiveByCategoryPK.as_view(), name='blog_archive_by_category_pk'),
    path('blog/<str:slug>/', views.BlogSingle.as_view(), name='blog_single'),
    path('create/videocast_category/', views.VideocastCategoryCreateView.as_view(), name='videocast_category_create'),
    path('videocast/', views.Videocast.as_view(), name='videocast'),
    path('create/videocast/', views.VideocastCreateView.as_view(), name='videocast_create'),
    path('videocast/<int:pk>/', views.VideocastArchiveByCategoryPK.as_view(), name='videocast_archive_by_category_pk'),
    path('videocast/<str:slug>/', views.VideocastSingle.as_view(), name='videocast_single'),
    path('create/podcast_category/', views.PodcastCategoryCreateView.as_view(), name='podcast_category_create'),
    path('podcast/', views.Podcast.as_view(), name='podcast'),
    path('create/podcast/', views.PodcastCreateView.as_view(), name='podcast_create'),
    path('podcast/<int:pk>/', views.PodArchiveByCategoryPK.as_view(), name='podcast_archive_by_category_pk'),
    path('podcast/<str:slug>/', views.PodSingle.as_view(), name='podcast_single'),
    path('create/skill/', views.SkillCreateView.as_view(), name='skill_create'),
]

templates/base.html
{% load static %}
{% load i18n %}
{% get_media_prefix as MEDIA_URL %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ config.SITE_TITLE }}</title>
    <meta name="description" content="{{ config.SITE_DESCRIPTION }}">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static '/assets/css/main.css' %}"/>
    <link rel="icon" href="{{ MEDIA_URL }}{{ config.SITE_FAVICON }}" type="image/png" sizes="16x16">
</head>
<body class="is-preload">

<!-- Wrapper -->
<div id="wrapper">

    <!-- Main -->
    <div id="main">
        <div class="inner">

            <!-- Header -->
            <header id="header">
                <a href="{% url 'content:index' %}" class="logo"><strong>{{ config.SITE_TITLE }}</strong></a>
                <ul class="icons">
                    {% if config.SOCIAL_NETWORKS_TWITTER_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_TWITTER_URL }}" class="icon brands fa-twitter"
                               title="Twitter"><span class="label">{% translate 'Twitter' %}</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_FACEBOOK_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_FACEBOOK_URL }}" class="icon brands fa-facebook-f"
                               title="Facebook"><span class="label">{% translate 'Facebook' %}</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_SNAPCHAT_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_SNAPCHAT_URL }}" class="icon brands fa-snapchat-ghost"
                               title="Snapchat"><span class="label">{% translate 'Snapchat' %}</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_INSTAGRAM_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_INSTAGRAM_URL }}" class="icon brands fa-instagram"
                               title="Instagram"><span class="label">{% translate 'Instagram' %}</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_MEDIUM_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_MEDIUM_URL }}" class="icon brands fa-medium-m"
                               title="Medium"><span class="label">{% translate 'Medium' %}</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_TELEGRAM_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_TELEGRAM_URL }}" class="icon brands fa-telegram"
                               title="Telegram"><span class="label">{% translate 'Telegram' %}</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_GITHUB_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_GITHUB_URL }}" class="icon brands fa-github"
                               title="Github"><span class="label">{% translate 'Github' %}</span></a></li>
                    {% endif %}
                    {% if config.SOCIAL_NETWORKS_GITLAB_URL != '#' %}
                        <li><a href="{{ config.SOCIAL_NETWORKS_GITLAB_URL }}" class="icon brands fa-gitlab"
                               title="Gitlab"><span class="label">{% translate 'Gitlab' %}</span></a></li>
                    {% endif %}
                </ul>
            </header>
            <!-- /Header -->

            {% block content %}
            {% endblock %}

        </div>
    </div>

    <!-- Sidebar -->
    <div id="sidebar">
        <div class="inner">

            <!-- Search -->
            <section id="search" class="alt">
                <form method="GET" action="{% url 'content:search' %}">
                    <input type="text" name="query" id="query" placeholder="{% translate 'Search' %}" required>
                </form>
            </section>
            <!-- /Search -->

            <!-- Menu -->
            <nav id="menu">
                <header class="major">
                    <h2>Menu</h2>
                </header>
                <ul>
                    <li><a href="{% url 'content:index' %}">{% translate 'Home Page' %}</a></li>
                    <li><a href="{% url 'content:blog' %}">{% translate 'Blog' %}</a></li>
                    <li>
                        <span class="opener">{% translate 'Blog Categories' %}</span>
                        <ul>
                            {% for blog_category in blog_categories %}
                                <li><a href="{% url 'content:blog_archive_by_category_pk' blog_category.pk %}">{{ blog_category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="{% url 'content:videocast' %}">{% translate 'Videocast' %}</a></li>
                    <li>
                        <span class="opener">{% translate 'Videocast Categories' %}</span>
                        <ul>
                            {% for videocast_category in videocast_categories %}
                                <li><a href="{% url 'content:videocast_archive_by_category_pk' videocast_category.pk %}">{{ videocast_category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="{% url 'content:podcast' %}">{% translate 'Podcast' %}</a></li>
                    <li>
                        <span class="opener">{% translate 'Podcast Categories' %}</span>
                        <ul>
                            {% for podcast_category in podcast_categories %}
                                <li><a href="{% url 'content:podcast_archive_by_category_pk' podcast_category.pk %}">{{ podcast_category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% if user.is_anonymous %}
                    <li><a href="{% url 'login' %}">{% translate 'Login' %}</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">{% translate 'Logout' %}</a></li>

                    <li>
                        <span class="opener">{% translate 'Create New Objects' %}</span>
                        <ul>
                            <li><a href="{% url 'content:blog_create' %}">{% translate 'New Blog' %}</a></li>
                            <li><a href="{% url 'content:videocast_create' %}">{% translate 'New Videocast' %}</a></li>
                            <li><a href="{% url 'content:podcast_create' %}">{% translate 'New Podcast' %}</a></li>
                            <li><a href="{% url 'content:skill_create' %}">{% translate 'New Skill' %}</a></li>
                        </ul>
                    </li>
                    <li>
                        <span class="opener">{% translate 'Create Category Object' %}</span>
                        <ul>
                            <li><a href="{% url 'content:blog_category_create' %}">{% translate 'New Blog Category' %}</a></li>
                            <li><a href="{% url 'content:videocast_category_create' %}">{% translate 'New Video Cast Category' %}</a></li>
                            <li><a href="{% url 'content:podcast_category_create' %}">{% translate 'New Podcast Category' %}</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            <!-- /Menu -->

            <!-- Section - podcast -->
            <section id="podcast">
                <header class="major">
                    <h2>{% translate 'The latest Podcasts' %}</h2>
                </header>
                <div class="mini-posts">
                    {% for podcast in podcasts %}
                        <article>
                            <a href="{% url 'content:podcast_single' podcast.slug %}" class="image">
                                <img src="{{ podcast.thumbnail.url }}" alt="{{ podcast.title }}"/>
                            </a>
                            <p>{{ podcast.content | safe |truncatewords_html:15 }}</p>
                            <a href="{% url 'content:podcast_single' podcast.slug %}" class="button">{% translate 'More' %}</a>
                        </article>
                    {% endfor %}
                </div>
            </section>
            <!-- /Section - podcast -->

            {% if config.GET_IN_TOUCH_ACTIVE == 'yes' %}
                <!-- get_in_touch -->
                <section id="get_in_touch">
                    <header class="major">
                        <h2>{% translate 'Get in touch' %}</h2>
                    </header>
                    <p>{{ config.GET_IN_TOUCH_INFO | safe }}</p>
                    <ul class="contact">
                        <li class="icon solid fa-envelope">
                            <a href="mailto:{{ config.GET_IN_TOUCH_EMAIL_ADDRESS }}">{{ config.GET_IN_TOUCH_EMAIL_ADDRESS }}</a>
                        </li>
                        <li class="icon solid fa-phone">
                            {{ config.GET_IN_TOUCH_PHONE }}
                        </li>
                        <li class="icon solid fa-home">
                            {{ config.GET_IN_TOUCH_ADDRESS | safe }}
                        </li>
                    </ul>
                </section>
                <!-- /get_in_touch -->
            {% endif %}

            <!-- Footer -->
            <footer id="footer">
                <p class="copyright">
                    &copy; Untitled. All rights reserved. Design: <a href="https://html5up.net">HTML5 UP</a>. CMS: <a
                        href="https://github.com/mavenium/PyEditorial" title="PyEditorial">PyEditorial</a></p>
            </footer>
            <!-- /Footer -->

        </div>
    </div>

</div>

<!-- Scripts -->
<script src="{% static '/assets/js/jquery.min.js' %}"></script>
<script src="{% static '/assets/js/browser.min.js' %}"></script>
<script src="{% static '/assets/js/breakpoints.min.js' %}"></script>
<script src="{% static '/assets/js/util.js' %}"></script>
<script src="{% static '/assets/js/main.js' %}"></script>
<!-- /Scripts -->

{% block custom_script %}
{% endblock custom_script %}

</body>
</html>

templates/blog_archive.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <!-- Section - archive -->
    <section id="archive">
        <header class="major">
            <h2>
                {% translate 'Blog Archive' %}
            </h2>
        </header>
        <div class="posts">
            {% for object in object_list %}
                <article>
                    <a href="{% url 'content:blog_single' object.slug %}" class="image" title="{{ object.title }}">
                        <img src="{{ object.thumbnail.url }}" alt="{{ object.title }}"/>
                    </a>
                    <h3>{{ object.title }}</h3>
                    <p>{{ object.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'content:blog_single' object.slug %}" class="button" title="{{ object.title }}">
                                {% translate 'More' %}
                            </a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - archive -->
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    {% for last_post in last_blog %}
        <!-- Banner -->
        <section id="banner">
            <div class="content">
                <header>
                    <h1>{{ last_post.title }}</h1>
                </header>
                <p>{{ last_post.content | safe | truncatewords_html:30 }}</p>
                <ul class="actions">
                    <li>
                        <a href="{% url 'content:blog_single' last_post.slug %}" class="button big" title="{{ last_post.title }}">
                            {% translate 'Learn More' %}
                        </a>
                    </li>
                </ul>
            </div>
            <span class="image object">
                <img src="{{ last_post.thumbnail.url }}" alt="{{ last_post.title }}"/>
            </span>
        </section>
        <!-- /Banner -->
    {% endfor %}

    <!-- Section - Skills -->
    <section id="skills">
        <header class="major">
            <h2>{% translate 'Skills' %}</h2>
        </header>
        <div class="features">
            {% for skill in skills %}
                <article>
                    <span class="icon solid {{ skill.icon }}"></span>
                    <div class="content">
                        <h3>{{ skill.title }}</h3>
                        <p>{{ skill.description }}</p>
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section -->

    <!-- Section - blog -->
    <section id="blog">
        <header class="major">
            <h2>{% translate 'The latest Blogs' %}</h2>
        </header>
        <div class="posts">
            {% for blog_post in blogs %}
                <article>
                    <a href="{% url 'content:blog_single' blog_post.slug %}" class="image" title="{{ blog_post.title }}">
                        <img src="{{ blog_post.thumbnail.url }}" alt="{{ blog_post.title }}"/>
                    </a>
                    <h3>{{ blog_post.title }}</h3>
                    <p>{{ blog_post.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'content:blog_single' blog_post.slug %}" class="button" title="{{ blog_post.title }}">{% translate 'More' %}</a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - blog -->

    <!-- Section - Video Cast -->
    <section id="videocast">
        <header class="major">
            <h2>{% translate 'The latest Video Casts' %}</h2>
        </header>
        <div class="posts">
            {% for videocast in videocasts %}
                <article>
                    <a href="{% url 'content:videocast_single' videocast.slug %}" class="image" title="{{ videocast.title }}">
                        <img src="{{ videocast.thumbnail.url }}" alt="{{ videocast.title }}"/>
                    </a>
                    <h3>{{ videocast.title }}</h3>
                    <p>{{ videocast.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'content:videocast_single' videocast.slug %}" class="button" title="{{ videocast.title }}">{% translate 'More' %}</a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - Video Cast -->
{% endblock %}

templates/podcast_archive.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <!-- Section - archive -->
    <section id="archive">
        <header class="major">
            <h2>
                {% translate 'Podcast Archive' %}
            </h2>
        </header>
        <div class="posts">
            {% for object in object_list %}
                <article>
                    <a href="{% url 'content:podcast_single' object.slug %}" class="image" title="{{ object.title }}">
                        <img src="{{ object.thumbnail.url }}" alt="{{ object.title }}"/>
                    </a>
                    <h3>{{ object.title }}</h3>
                    <p>{{ object.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'content:podcast_single' object.slug %}" class="button" title="{{ object.title }}">
                                {% translate 'More' %}
                            </a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - archive -->
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block content %}
    <section id="archive">
        <header class="major">
            <h2>Search Result</h2>
        </header>
        <div>
            {% for blog in blogs %}
                <article>
                    <a href="{% url 'content:blog_single' blog.slug %}" title="{{ blog.title }}">
                        <h3>{{ blog.title }}</h3>
                    </a>                    
                    <p>{{ blog.content | safe | truncatewords_html:10 }}</p>
                </article>
                <hr>
            {% endfor %}
            
            {% for videocast in videocasts %}
                <article>
                    <a href="{% url 'content:videocast_single' videocast.slug %}" title="{{ videocast.title }}">
                        <h3>{{ videocast.title }}</h3>
                    </a>                    
                    <p>{{ videocast.content | safe | truncatewords_html:10 }}</p>
                </article>
                <hr>
            {% endfor %}

            {% for podcast in podcasts %}
                <article>
                    <a href="{% url 'content:podcast_single' podcast.slug %}" title="{{ podcast.title }}">
                        <h3>{{ podcast.title }}</h3>
                    </a>                    
                    <p>{{ podcast.content | safe | truncatewords_html:10 }}</p>
                </article>
                <hr>
            {% endfor %}                        
        </div>
    </section>
{% endblock %}

templates/single.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <!-- Content -->
    <section>
        <header class="main">
            <h1>{{ object.title }}</h1>
        </header>

        <span class="image main">
            <img src="{{ object.thumbnail.url }}" alt="{{ object.title }}"/>
        </span>

        {{ object.content | safe }}

        {% if object.video %}
            <a href="{{ object.video }}" class="button primary fit icon solid fa-video">{% translate 'Show Video' %}</a>
        {% endif %}

        {% if object.audio %}
            <a href="{{ object.audio.url }}" class="button primary fit icon solid fa-download">{% translate 'Download Audio' %}</a>
        {% endif %}

    </section>
    <!-- /Content -->
{% endblock %}

templates/video_cast_archive.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <!-- Section - archive -->
    <section id="archive">
        <header class="major">
            <h2>
                {% translate 'Video Cast Archive' %}
            </h2>
        </header>
        <div class="posts">
            {% for object in object_list %}
                <article>
                    <a href="{% url 'content:videocast_single' object.slug %}" class="image" title="{{ object.title }}">
                        <img src="{{ object.thumbnail.url }}" alt="{{ object.title }}"/>
                    </a>
                    <h3>{{ object.title }}</h3>
                    <p>{{ object.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'content:videocast_single' object.slug %}" class="button" title="{{ object.title }}">
                                {% translate 'More' %}
                            </a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - archive -->
{% endblock %}

templates/videocast_archive.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <!-- Section - archive -->
    <section id="archive">
        <header class="major">
            <h2>
                {% translate 'Videocast Archive' %}
            </h2>
        </header>
        <div class="posts">
            {% for object in object_list %}
                <article>
                    <a href="{% url 'content:videocast_single' object.slug %}" class="image" title="{{ object.title }}">
                        <img src="{{ object.thumbnail.url }}" alt="{{ object.title }}"/>
                    </a>
                    <h3>{{ object.title }}</h3>
                    <p>{{ object.content | safe | truncatewords_html:30 }}</p>
                    <ul class="actions">
                        <li>
                            <a href="{% url 'content:videocast_single' object.slug %}" class="button" title="{{ object.title }}">
                                {% translate 'More' %}
                            </a>
                        </li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
    <!-- /Section - archive -->
{% endblock %}